version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONGO_URI=mongodb://mongo:27017/jobfilter
    depends_on:
      - mongo
    networks:
      - jobnet

  mongo:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    networks:
      - jobnet
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

networks:
  jobnet: